version: '2'
services:
  web:
    image: nginx:alpine
    restart: 'on-failure'
    ports:
    - "80:80"
    volumes:
    - ./www:/www
    - ./logs:/etc/nginx/logs
    - ./nginx.conf:/etc/nginx/nginx.conf
